apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: byy83l1in-nodejs
  janus-idp.io/tekton: byy83l1in-nodejs
  backstage.io/kubernetes-id: byy83l1in-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: byy83l1in-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
