apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: byy83l1in-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: byy83l1in-nodejs 
  name: byy83l1in-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: byy83l1in-nodejs 
